### ISSUE TITLE
北海道一周したい（準備）

### ISSUE THREAD

**Issue by mokocm** [mokocm/diet#18]
# 背景
GWを利用して北海道を一周して体脂肪率を減らしたい。また、長期休暇を取って心身共にリフレッシュしたい。
そのため、ロングライドをするにあたって諸々の調整、準備をして実行する必要がある。

# 受け入れ条件
- [x] GWにプラスで1週間休みを取る調整をする(4/29〜5/15、計17日間)
- [x] キャンプ道具を含む装備を調整すること
- [x] 雨天の装備を整えて、雨の日でも走れるようにすること
- [x] 現実的なルートの設定を行い、Garminにルート登録をすること
- [x] 2週間連続で150km走っても大丈夫なように体を整えること
- [x] バイクをメンテして、ロングライドしても問題ない事を確認すること

**Comment by mokocm** [comment]
## 装備
- [x] サイクルウェア
- [x] 替えの服（サイクルウェアを洗濯するときに使う。半袖短パンで問題無し）
- [ ] 雨用
  - [ ] レインウェア
  - [ ] シューズカバー
- [ ] キャンプ用
  - [x] テント
  - [ ] マット 
  - [ ] 火使って調理する機具
  - [ ] モバイルバッテリー(容量多め)
- [ ] パンク修理用道具
  - [x] CO2ボンベたくさん
  - [ ] チューブラーで行く想定なので念のため[マルニ クイックショット](https://www.amazon.co.jp/dp/B00AAPY0ZQ)を買う

### Tasks
- [x] フロントタイヤ交換 & シーラント入れる
- [ ] リアタイヤ交換 & シーラント入れる

**Comment by mokocm** [comment]
## 購入するもの
- [ ] [レインウェア](https://webshop.montbell.jp/goods/list.php?category=1000)
- [ ] 短パンビブショーツ（店頭で購入）
- [x] [シューズカバー](https://www.amazon.co.jp/dp/B09CPNV5ZP/)
- [x] [モバイルバッテリー](https://www.amazon.co.jp/dp/B08GC3JDSQ)
- [x] [銀マット](https://www.amazon.co.jp/dp/B00NFAB6PU/)
- [x] [サドルバッグ](https://www.amazon.co.jp/dp/B07763PC72?th=1)
- [x] [携帯ポンプ](https://www.amazon.co.jp/dp/B01GE0LBJI)

**Comment by mokocm** [comment]
合計 2275km 10日間

1. [札幌→みさき台公園 203.24km 2,793m](https://www.strava.com/routes/2953215833477647122)
2. [みさき台公園→日の出岬 283.76km 1,053m](https://www.strava.com/routes/2953216982313097812)
3. [日の出岬→斜里 182.11km 860m]
4. 斜里→知床峠→根室 208.34km 1,956m
5. 根室→釧路 199.17km 1,878m
6. 釧路→新ひだか 275.27km 2,675m
7. 新ひだか→室蘭 155.46km 654m 
8. 室蘭→函館 254.70km 1,817m
9. 函館→せたな町 240.52km 2,108m
10. せたな町→札幌 272.53km 5,019m

**Comment by mokocm** [comment]
## ルート

1. [札幌→天塩 240.40km 2,966m](https://www.strava.com/routes/2953215833477647122)
2. [天塩→紋別278.19km 1,108m](https://www.strava.com/routes/2953216982313097812)
3. [紋別→知床峠→標津 266.72km 2,070m](https://www.strava.com/routes/2953218077270580820)
4. [標津→釧路288.20km 2,351m](https://www.strava.com/routes/2953219162586523220)
5. [釧路→門別308.90km 2,931m](https://www.strava.com/routes/2953220585194818132)
6. [門別→森 302.51km 1,597m](https://www.strava.com/routes/2953222510386509416)
7. [森→せたな町303.96km 2,641m](https://www.strava.com/routes/2953223676395373160)
8. [せたな町→札幌275.08km 5,136m](https://www.strava.com/routes/2953224665233639016)

**Comment by mokocm** [comment]
![IMG_2270](https://user-images.githubusercontent.com/52817048/165686658-e7ccda04-a9a5-4f1f-9a3d-385d2ea2b811.jpg)

**Comment by mokocm** [comment]
![image](https://user-images.githubusercontent.com/52817048/165692333-8ec6214f-600c-4fa3-b255-8c2106f1513f.jpeg)
